CREATE TABLE IF NOT EXISTS posts
(
    `id` INT(11) AUTO_INCREMENT NOT NULL,
    `name` VARCHAR(31) CHARACTER SET utf8 NOT NULL,
    `message` LONGTEXT CHARACTER SET utf8 NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);
